services:
  mc:
    image: itzg/minecraft-server:2024.10.2-java8-jdk
    restart: on-failure:3
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /minecraftServer:/data
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.16.5"
      FORGE_VERSION: "36.2.42"
      MEMORY: '6G'
      JVM_OPTS: "-Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
  
  proetheus:
    image: bitnami/prometheus:3.0.0
    tty: true
    stdin_open: true
    ports:
      - "9090:9090"
    volumes:
      # The path on your local computer where the prometheus configuration exists mapped to /etc/prometheus/prometheus.yml within the prometheus container
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure:3
  
  grafana:
    image: grafana/grafana:11.3.1
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      # The path on your local computer where the grafana data will be written to mapped to /var/lib/grafana inside the grafana container
      - ./grafana:/var/lib/grafana
    restart: on-failure:3