services:
  mc:
    image: itzg/minecraft-server:2024.10.2-java8-jdk
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /minecraftServer/
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.16.5"
      FORGE_VERSION: "136.2.42"