global:
  scrape_interval: 30s 


scrape_configs:
  # scrape minecraft server
- job_name: 'minecraft'
  static_configs:
    - targets: ['188.120.229.122:19565']
      labels:
        server_name: 'minecraft-docker'
